language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: djZR5cykFl/q2ltz7oylGASZAkeGcElE0gjfpJoDktSI/vJaNAV/IDKftOpulWxDtj/cjSI/fexCqwCe62i3V1p68lH/Zi4IlsGH2EloKH2uciloAnqwF/BIalgT6tZebxfmO76aU/o3mmwt1aBPfrrK212ElWpI/aUh022AUtU7vs+mAQUA0YCUZ4V5RRB1KKA+lrS9waSUUzz9ZNRnhgx34xwoVvi3WiY09kRvvKrCjnU6ruydu9if9VtqngkIvubpMaJTNqRyawzt7/KGdj4muUT+IjoGWdQGBBRt6k3zGBIypkIM/0TMJFY19DmEHSKDQ4d0q0yRKrcqj50UqVKSUxBgva/AGrIiPgpTbVJ1pjOJ2YrjhhfPLxwwMprQvbiQ9SSckouAfN6Rn6CmATqHaAkeVLJhgUNs5X7jyGmrA8tznENKsGPgOoPQByaULOCiaWrKtFs8kFcyJctkdutw5TQMQqaGkHwCQbloTOnZXnejtrRyl2hSs/aemQm+bCXFAt3mo9Qc8ZNNQCzzQF1QkqZgeHlI0bPtlq64a4ILUwrh6683gMKEOx8XOa39qq+7H8UMxk8JSqJDaa86MxdRIT7IfAh/wsKxF3hUIX9F7M/gdvluQLvktfg+JACobe9bXYuqC3UZ2neKXS50Ls8DUr+jWbb8znRDCUw9OCU=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-rollup
